# -*- coding: utf-8 -*-
"""Looker Filter passed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xUBMElS5BFzFYqHjVuuvBmMz5hvbq5f3

# **Prerequisites**
"""

pip install looker_sdk

pip install python-pptx

"""# **Create a looker.ini file with the API clientID and key using the following format:**

> Indented block



```
[Looker]
#Base URL for API. Do not include /api/* in the url
base_url=insert_url_here
# API 3 client id
client_id=YourClientID
# API 3 client secret
client_secret=YourClientSecret
# Set to false if testing locally against self-signed certs. Otherwise leave True
verify_ssl=True

# Client ID and Client Secret can be obtained from Looker -> Admin -> Users -> API Keys



```

Used this example for passing filters: https://python.plainenglish.io/use-python-and-looker-sdk-to-automate-looker-report-generation-e22ba4b0c1f2

If the filter key does not exist on all the tiles, the query will return no results.

Example: if for GRID we are using grid.id, publications__research_orgs__unnested.grid_id will return no results

# **Main Code**

Update below the dashboard_id and filter_dict with the desired filters
"""

import looker_sdk #access looker objects
from looker_sdk import models
import base64 #encode looker image into .png file
import os
import base64
from pptx import Presentation
from pptx.util import Inches

sdk = looker_sdk.init40('/content/looker.ini')
# Set the dashboard_id
dashboard_id = "insert_dashboard_id_here"

#Set the filters
filter_dict = {'view_name.filter_name': 'filter_value',
               'iew_name.filter_name': 'filter_value'}

dashboard = sdk.dashboard(dashboard_id)
dashboard_name = dashboard.title

# Get the dashboard elements
dashboard_elements = sdk.dashboard_dashboard_elements(dashboard_id)

# Get the dashboard layouts
dashboard_layouts = sdk.dashboard_dashboard_layouts(dashboard_id)

# Create a mapping of element_id to layout information for quick access
layout_mapping = {layout.dashboard_element_id: layout for component in dashboard_layouts for layout in component.dashboard_layout_components}

# Sort the dashboard elements based on the position (row, column ascending)
dashboard_elements = sorted(dashboard_elements, key=lambda element: (layout_mapping[element.id].row, layout_mapping[element.id].column))

# Create a PowerPoint presentation
presentation = Presentation()

# Add a title slide
title_slide_layout = presentation.slide_layouts[0]
title_slide = presentation.slides.add_slide(title_slide_layout)
title = title_slide.shapes.title
subtitle = title_slide.placeholders[1]

title.text = dashboard_name
# Include filter information in the subtitle
filter_info = "\n".join([f"{key}: {value}" for key, value in filter_dict.items()])
subtitle.text = filter_info

# Iterate through the saved PNG files and add each as a new slide
for element in dashboard_elements:
    if element.title is not None:
        title = element.title
        altered_query = element.query

        if altered_query is not None:
            # Add a new slide
            slide_layout = presentation.slide_layouts[5]  
            slide = presentation.slides.add_slide(slide_layout)

            # Add title to the slide
            title_placeholder = slide.placeholders[0]
            title_placeholder.text = title

            try:
                # Create a copy of the tile query to apply filters
                altered_query = element.query

                # If the query has existing filters, append the dashboard filters
                if 'filters' in altered_query:
                    altered_query.filters.update(filter_dict)
                else:
                    altered_query['filters'] = filter_dict

                # Remove the client id and id from the query to create a new query
                altered_query.client_id = None
                altered_query.id = None

                # Run the query with applied filters inline (doesn't create a new query object) and save as .png file
                query_image = sdk.run_inline_query(body=altered_query, result_format='png')
                image_string = base64.b64encode(query_image)
                image_file = f"{title}.png"

                # Save the image to a file
                with open(image_file, "wb") as fh:
                    fh.write(base64.decodebytes(image_string))

                # Add the image to the slide
                left = Inches(1)
                top = Inches(2)
                pic = slide.shapes.add_picture(image_file, left, top, width=Inches(5))

                # Remove the PNG file
                os.remove(image_file)
            except Exception as e:
                print(f"Error running query for element {title}: {e}")
        else:
            print(f"Query is None for element: {title}")

# Save the PowerPoint presentation with the name of the dashboard
presentation.save(f"{dashboard_name}.pptx")
